Use a `bp_read` cap to handle community visibility
buddypress/buddypress pull request #25
Opened 2022-10-09 17:06 UTC by imath

The main idea is to unset the `buddypress()->pages` when the user hasn't the WP Cap mapped to a new `bp_read` one. As a result BP Globals like `current_component`, `current_action` and `action_variables` are not set and we end up into a `! is_buddypress()` area for not logged in members when the community visibility option is set to `members`. Activity RSS feed are then not set. I believe if we use this scenario, we'll need to edit the BP Rest API endpoints to use the `bp_current_user_can( 'bp_read' )` into the permissions_check methods.

A benefit of this is the site admin can easily customize the default content displayed to not logged in members using the Block Editor for the corresponding BP Pages.

Trac ticket: https://buddypress.trac.wordpress.org/ticket/8734

---
**This Pull Request is for code review only. Please keep all other discussion in the BuddyPress Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the WordPress Core Handbook for more details.**

2022-10-16 14:10 UTC, imath commented on src/bp-core/bp-core-catchuri.php
> +	if ( ! bp_current_user_can( 'bp_read', $bp_uri_globals ) && ! in_array( $bp_uri_globals['current_component'], array( 'register', 'activate' ), true ) ) {
Here's an example to let any user access to the members directory:

```php
function leave_members_component_visible( $caps, $cap, $user_id, $args ) {
	$r = reset( $args );

	if ( 'bp_read' === $cap && isset( $r['current_component'] ) && 'members' === $r['current_component'] ) {
		$caps = array( 'exist' );
	}

	return $caps;
}
add_filter( 'bp_map_meta_caps', 'leave_members_component_visible', 10, 4 );
```

2022-12-27 23:44 UTC, renatonascalves requested changes
Left a few suggestions!

2022-12-27 23:44 UTC, renatonascalves commented on src/bp-core/classes/class-bp-core.php
> +				add_filter( 'bp_replace_the_content', array( $this, 'gate_content' ) );
add phpdoc?

2022-12-27 23:44 UTC, renatonascalves commented on src/bp-core/classes/class-bp-core.php
> +	 */
Missing `@return`

2022-12-27 23:44 UTC, renatonascalves commented on src/bp-core/classes/class-bp-core.php
> +	 *
PHPDoc: `@global BuddyPress $bp The one true BuddyPress instance.`

2022-12-27 23:44 UTC, renatonascalves commented on src/bp-core/bp-core-template.php
> +		)
This might prove problematic. Imagine if I hook here and pass something like this: `<a><span></span></a>`...

2022-12-27 23:44 UTC, renatonascalves commented on src/bp-core/bp-core-options.php
> +	return apply_filters( 'bp_get_community_visibility', bp_get_option( '_bp_community_visibility', $default ) );
I'd suggest passing the `$default` as a second parameter.

2022-12-27 23:44 UTC, renatonascalves commented on src/bp-core/bp-core-functions.php
> +	$slug = apply_filters( 'bp_core_community_gate_slug', __( 'community-gate', 'buddypress' ) );
Missing phpdoc?

2023-04-23 06:42 UTC, imath commented
A new & improved way of dealing with this visibility feature will be soon worked on.

2023-04-23 06:42 UTC, closed without merging