Template hierarchy
buddypress/buddypress pull request #299
Opened 2024-05-29 16:23 UTC by vapvarun

Trac ticket: [https://github.com/buddypress/bp-documentation/issues/247](https://github.com/buddypress/bp-documentation/issues/247)

---
**This Pull Request is for code review only. Please keep all other discussion in the BuddyPress Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the WordPress Core Handbook for more details.**

2024-08-18 10:13 UTC, imath commented
I don't forget I have to review this PR @vapvarun! I'll try to do it asap. I believe it's lacking `current_theme_supports( 'BuddyPress' )` template hierarchy and soon the Block Theme template hierarchy 😅 but it's already a great contribution and file system trees are lovely 😍

2024-08-27 02:01 UTC, renatonascalves requested changes

2024-08-31 21:17 UTC, emaralive commented
@vapvarun, @imath & @renatonascalves, 

Amongst the 3 of you, take a look at trac ticket [5360 - Template hierarchy file names Codex guide?](https://buddypress.trac.wordpress.org/ticket/5360) and see if there is any relevancy, e.g., has this been a consideration for inclusion within the documentation?

2024-09-06 20:09 UTC, imath requested changes
Hi @vapvarun 

Thanks for your work on this 😍 💪. It's a nice introduction to BP Template Hierarchy and it's probably enough for advanced users.

I believe Theme developers will need more informations such as ways to customize a template part according to the displayed user, member type, etc...

I agree with @renatonascalves it's important to quickly explain the base template used by BuddyPress to inject community content within the post content.

2024-09-10 17:36 UTC, closed without merging