Start Documenting  BP REST API v2
buddypress/buddypress pull request #382
Opened 2024-10-07 00:00 UTC by imath

Adds the following page to developer doc:
- Introduction about the BP REST API
- Reference: list of REST API Routes
- Components routes
- Members routes

Working on these docs made me suggesting improvements about Components and Members REST controllers, @renatonascalves could you have a look at these?

See https://github.com/buddypress/bp-documentation/issues/298

---
**This Pull Request is for code review only. Please keep all other discussion in the BuddyPress Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the WordPress Core Handbook for more details.**

2024-10-07 13:01 UTC, renatonascalves requested changes

2024-10-07 13:01 UTC, renatonascalves commented on docs/developer/execution-contexts/rest-api/README.md
> +> This is the documentation for the BP REST API **v2**. This version was introduced in BuddyPress 15.0.0. The BP REST API v1 is deprecated as of BuddyPress 15.0.0. If you still need to use v1, you ca
```suggestion
> This is the documentation for the BP REST API **v2**. This version was introduced in BuddyPress 15.0.0. The BP REST API v1 is deprecated as of BuddyPress 15.0.0. If you still need to use v1, you can download and activate the archived [BuddyPress RESTful API plugin](https://github.com/buddypress/BP-REST) and refer to this [documentation](https://developer.buddypress.org/bp-rest-api/). We strongly advise you to update your code to support **v2** as soon as you can.
```

2024-10-07 13:01 UTC, renatonascalves commented on docs/developer/execution-contexts/rest-api/README.md
> +> This is the documentation for the BP REST API **v2**. This version was introduced in BuddyPress 15.0.0. The BP REST API v1 is deprecated as of BuddyPress 15.0.0. If you still need to use v1, you ca
Based on your recent comment [here](https://wordpress.slack.com/archives/C02RQBYUG/p1727896648522939).

2024-10-07 13:02 UTC, renatonascalves commented on src/bp-core/classes/class-bp-core-components-rest-controller.php
> -						'type'        => 'array',
The change looks good, but it looks to me the type of the data being returned is not an `object`.

2024-10-07 13:05 UTC, renatonascalves commented
There is one unit test failing due to a flaky unit test. I've been trying to identify why it fails sometimes only. You can usually rerun the failed action to "fix" it. While I try to come up with a _final_ fix.

![CleanShot 2024-10-07 at 10 03 23@2x](https://github.com/user-attachments/assets/9cecf1b8-419a-4db3-bc60-d55b091887a4)

2024-10-08 03:01 UTC, imath commented on src/bp-core/classes/class-bp-core-components-rest-controller.php
> -						'type'        => 'array',
I agree in PHP a non numeric associative array is sent by the controller. But as it's a non numeric associative array, the JSON response treat it as an object:
 
<img width="292" alt="Capture d’écran 2024-10-08 à 04 55 16" src="https://github.com/user-attachments/assets/c4a761a8-c634-4ced-b6d8-a0d1437adffe">

I'm wondering, should we consider the JSON response or the PHP part to type schema properties?

2024-10-08 11:30 UTC, renatonascalves commented on src/bp-core/classes/class-bp-core-components-rest-controller.php
> -						'type'        => 'array',
Interesting.

2024-10-08 11:31 UTC, renatonascalves commented on src/bp-core/classes/class-bp-core-components-rest-controller.php
> -						'type'        => 'array',
I think we should consider the JSON response, that's what the REST API consumers will see. Not the PHP version of the data.

2024-10-08 13:44 UTC, renatonascalves approved these changes

2024-10-09 04:38 UTC, closed without merging